[package]
name = "httpserver"
edition = "2021"

[dependencies]
askama = "0.14.0"
axum = { version = "0.8.4", features = ["ws"] }
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
comrak = "0.39.0"
ammonia = "4.1.0"
