[package]
name = "httpserver"
edition = "2021"

[dependencies]
axum = "0.7"
hyper = { version = "1", features = ["server", "http1"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
