[package]
name = "redis_example"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
redis = { version = "0.29.2", features = ["tokio-comp"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
chrono = "0.4"
futures = "0.3"
