[package]
name = "ws_state_machine"
edition = "2021"

[dependencies]
axum = { version = "0.8.3", features = ["ws"] }
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }
derivative = "2.2.0"
tokio = { version = "1", features = ["full"] }
