name: run

on:
  workflow_dispatch:
  push:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.out }}
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: list
        id: gen
        run: echo "out=$(find . -type d -name 'step??_*' | sort | sed 's|^\./||' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
  run:
    needs: list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.list.outputs.matrix) }}
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: ${{ matrix.dir }}
        run: (cd ${{ matrix.dir }}; ./run.sh)
